# https://github.com/KnpLabs/geekweek12/wiki/Routing


profile:
    pattern: /profile
    defaults: { _controller: App:Common:profile, controller: 'profile#show' }

imageProxy:
    pattern: /proxy
    defaults: { _controller: App:Common:imageProxy }

trackEvent:
    pattern: /trackEvent
    defaults: { _controller: App:Common:trackEvent }

imagesCountText:
    pattern: /imagesCountText
    defaults: { _controller: App:Common:imagesCountText }

faq:
    pattern: /faq
    defaults: { _controller: App:Common:faq }

_appGlobals:
    pattern: /app/globals.js
    defaults: { _controller: App:Common:appGlobals }

homepage:
    pattern: /
    defaults: { _controller: App:Common:homepage, controller: 'homepage#show' }

#_appRoute:
#    pattern: /{params}
#    defaults: { _controller: App:Common:dynamic }
#    requirements:
#      params: [\w\W]+
