
imageProxy:
    pattern: /proxy
    defaults: { _controller: App:Common:imageProxy }

trackEvent:
    pattern: /trackEvent
    defaults: { _controller: App:Common:trackEvent }

imagesCountText:
    pattern: /imagesCountText
    defaults: { _controller: App:Common:imagesCountText }

_appGlobals:
    pattern: /app/globals.js
    defaults: { _controller: App:Common:appGlobals }

faq:
    pattern: /faq
    defaults: { _controller: App:Public:faq, page_title: 'FAQ' }

contact:
    pattern: /contact
    defaults: { _controller: App:Public:contact, page_title: 'Contact' }

profile:
    pattern: /profile
    defaults: { _controller: App:Public:profile, controller: 'profile#show', page_title: 'Profile' }

homepage:
    pattern: /
    defaults: { _controller: App:Public:homepage, controller: 'homepage#show', page_title: '' }

sitemap:
    pattern: /sitemap.xml
    defaults: { _controller: App:Common:sitemap, _format: 'xml' }