
imageProxy:
    pattern: /proxy
    defaults: { _controller: App:Common:imageProxy }

trackEvent:
    pattern: /trackEvent
    defaults: { _controller: App:Common:trackEvent }

imagesCountText:
    pattern: /imagesCountText
    defaults: { _controller: App:Common:imagesCountText }

_appGlobals:
    pattern: /app/globals.js
    defaults: { _controller: App:Common:appGlobals }

faq:
    pattern: /{_locale}/faq
    defaults:
        _controller: App:Public:faq
        page_title: 'FAQ'
#        page_description: 'Frequently Asked Questions - find answers for usual questions how to use this service.'

contact:
    pattern: /{_locale}/contact
    defaults:
        _controller: App:Public:contact
        page_title: 'Contact'
#        page_description: 'In case you have a question or suggestion, please fill in following form and we will reply to you as soon as possible.'

profile:
    pattern: /{_locale}/profile
    defaults:
        _controller: App:Public:profile
        controller: 'profile#show'
        page_title: 'Profile'

localized_homepage:
    pattern: /{_locale}/
    defaults:
        _controller: App:Public:homepage
        controller: 'homepage#show'


homepage:
    pattern: /
    defaults:
        _controller: App:Public:homepage
        controller: 'homepage#show'
        page_title: 'Save, Download, Backup your Instagram photos '
#        page_description: 'instasavegram.com - an online tool to save all your Instagram photos to your PC, tablet and even phone. Save your Instagram images to your drive and share them via Facebook, Flickr or Google+.'

sitemap:
    pattern: /{_locale}/sitemap.xml
    defaults: { _controller: App:Common:sitemap, _format: 'xml' }